services:

  postgres_service:
    container_name: postgres_container
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - postres-network

  pgadmin_service:
    depends_on:
      - postgres_service
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
    - "5050:80"
    links:
      - postgres_service
    networks:
      - postres-network
    volumes:
      - .:/code

volumes:
  db-data:

networks:
  postres-network:
    driver: bridge
